name: Jekyll Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Jekyll site
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/srv/jekyll \
            jekyll/jekyll:latest \
            jekyll build
